# Generated by Powerlevel10k configuration wizard on 2024-08-26 at 10:47 -03.
# Based on romkatv/powerlevel10k/config/p10k-pure.zsh,
#
# Config file for Powerlevel10k with the style of Pure (https://github.com/sindresorhus/pure).
#

# Temporarily change options.
'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases' ]] || p10k_config_opts+=('aliases')
[[ ! -o 'sh_glob' ]] || p10k_config_opts+=('sh_glob')
[[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

() {
	#
	# Config Start
	#
	emulate -L zsh -o extended_glob
	# Unset all configuration options.
	unset -m '(POWERLEVEL9K_*|DEFAULT_USER)~POWERLEVEL9K_GITSTATUS_DIR'
	# Zsh >= 5.1 is required.
	[[ $ZSH_VERSION == (5.<1->*|<6->.*) ]] || return

	#
	# Prompt colors.
	#

	local grey='#464646'
	local red='#D24646'
	local green='#46D246'
	local cyan='#46D2D2'
	local white='#D2D2D2'

	#
	# Prompt segments.
	#

	# Left prompt segments.
	typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
		dir # currenttree directory
		vcs # git status
	)
	# Right prompt segments.
	typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
		prompt_char # prompt symbol
		command_execution_time # previous command duration
		context # user@host
	)

	# 
	# Prompt style.
	#

	# Basic style options that define the overall prompt look.
	typeset -g POWERLEVEL9K_BACKGROUND=# transparent background
	typeset -g POWERLEVEL9K_{LEFT,RIGHT}_{LEFT,RIGHT}_WHITESPACE=' ' # no surrounding whitespace.
	# The right end of left prompt.
	typeset -g POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL='\uE0B0'
	# The left end of right prompt.
	typeset -g POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL='\uE0B2'
	# The left end of left prompt.
	typeset -g POWERLEVEL9K_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL=
	# The right end of right prompt.
	typeset -g POWERLEVEL9K_RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL=''
	typeset -g POWERLEVEL9K_VISUAL_IDENTIFIER_EXPANSION= # no segment icons.
	# Add an empty line before each prompt except the first. This doesn't emulate the bug.
	typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=false

	#
	# Current directory.
	#
	
	# Truncate Current if too big.
	typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
	typeset -g POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
	typeset -g POWERLEVEL9K_SHORTEN_DELIMITER=
	typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=1
	# Color of current directory.
	typeset -g POWERLEVEL9K_DIR_FOREGROUND=$white
	typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=$cyan
	typeset -g POWERLEVEL9K_DIR_BACKGROUND=$grey

	#
	# Git Status Config.
	#

	# Disable async loading indicator to make directories that aren't Git repositories
	# indistinguishable from large Git repositories without known state.
	typeset -g POWERLEVEL9K_VCS_LOADING_TEXT=
	# Don't wait for Git status even for a millisecond, so that prompt always updates
	# asynchronously when Git state changes.
	typeset -g POWERLEVEL9K_VCS_MAX_SYNC_LATENCY_SECONDS=0

	#
	# Git Status Style.
	#

	# Grey Git prompt. This makes stale prompts indistinguishable from up-to-date ones.
	typeset -g POWERLEVEL9K_VCS_FOREGROUND=$cyan
	typeset -g POWERLEVEL9K_VCS_BACKGROUND=$grey
	# Cyan ahead/behind arrows.
	typeset -g POWERLEVEL9K_VCS_{INCOMING,OUTGOING}_CHANGESFORMAT_FOREGROUND=$cyan
	# Don't show remote branch, current tag or stashes.
	typeset -g POWERLEVEL9K_VCS_GIT_HOOKS=(vcs-detect-changes git-untracked git-aheadbehind)
	# Don't show the branch icon.
	typeset -g POWERLEVEL9K_VCS_BRANCH_ICON=' \u2000'
	# When in detached HEAD state, show @commit where branch normally goes.
	typeset -g POWERLEVEL9K_VCS_COMMIT_ICON='@'
	# Don't show staged, unstaged, untracked indicators.
	typeset -g POWERLEVEL9K_VCS_{STAGED,UNSTAGED,UNTRACKED}_ICON=
	# Show '●' when there are staged, unstaged or untracked files.
	typeset -g POWERLEVEL9K_VCS_DIRTY_ICON='●'
	# Show '' if local branch is behind remote.
	typeset -g POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON=':'
	# Show '' if local branch is ahead of remote.
	typeset -g POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON=':'
	# Don't show the number of commits next to the ahead/behind arrows.
	typeset -g POWERLEVEL9K_VCS_{COMMITS_AHEAD,COMMITS_BEHIND}_MAX_NUM=1
	# Remove space between '' and '' and all trailing spaces.
	typeset -g POWERLEVEL9K_VCS_CONTENT_EXPANSION='${${${P9K_CONTENT/* :/}// }//:/ }'

	#
	# Last Command Success or error indicator.
	#

	# Green prompt symbol if the last command succeeded.
	typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_FOREGROUND=$green
	typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_CONTENT_EXPANSION=''
	# Red prompt symbol if the last command failed.
	typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_FOREGROUND=$red
	typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_CONTENT_EXPANSION=''
	# Prompt Background
	typeset -g POWERLEVEL9K_PROMPT_CHAR_BACKGROUND=$grey

	#
	# Previous Command Time.
	#

	# Show previous command duration only if it's >= 5s.
	typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=
	# Don't show fractional seconds. Thus, 7s rather than 7.3s.
	typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=0
	# Duration format: 1d 2h 3m 4s.
	typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT='d h m s'
	# Yellow previous command duration.
	typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=$cyan
	typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=$grey

	#
	# User Context Style.
	#

	# Context format when root: user@host. The first part white, the rest grey.
	typeset -g POWERLEVEL9K_CONTEXT_ROOT_TEMPLATE="%F{$white}%n%f%F{$grey}@%m%f"
	# Context format when not root: user@host. The whole thing grey.
	typeset -g POWERLEVEL9K_CONTEXT_TEMPLATE="%n"
	typeset -g POWERLEVEL9K_CONTEXT_FOREGROUND=$white
	typeset -g POWERLEVEL9K_CONTEXT_BACKGROUND=$grey

	#
	# Other Configs.
	#

	# Transient prompt works similarly to the builtin transient_rprompt option. It trims down prompt
	# when accepting a command line. Supported values:
	typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=off
	# Instant prompt mode.
	typeset -g POWERLEVEL9K_INSTANT_PROMPT=verbose
	# Hot reload allows you to change POWERLEVEL9K options after Powerlevel10k has been initialized.
	typeset -g POWERLEVEL9K_DISABLE_HOT_RELOAD=true
	# If p10k is already loaded, reload configuration.
	(( ! $+functions[p10k] )) || p10k reload
}

# Tell `p10k configure` which file it should overwrite.
typeset -g POWERLEVEL9K_CONFIG_FILE=${${(%):-%x}:a}

(( ${#p10k_config_opts} )) && setopt ${p10k_config_opts[@]}
'builtin' 'unset' 'p10k_config_opts'
