# vim:ft=kitty
# Configs for kitty termnial
#

# Fonts
font_family						JetBrainsMono NF Regular
bold_font						JetBrainsMono NF Bold
italic_font						auto
bold_italic_font				auto
font_size						11
modify_font underline_position 	-1
modify_font underline_thickness 150%
modify_font strikethrough_position 2px

# Cursor
cursor							#D2D2D2
cursor_stop_blinking_after		5.0

# Mouse
mouse_hide_wait -1
url_color #0088D2
url_style curly

# Scrollbar
scrollback_indicator_opacity 0.0

# Terminal Bell
enable_audio_bell				no

# Color Scheme
foreground						#D2D2D2
background						#141414
color0							#141414
color1							#D21414
color2							#14D214
color3							#D2D214
color4							#1414D2
color5							#D214D2
color6							#14D2D2
color7							#D2D2D2
color8							#AAAAAA

selection_foreground			none
selection_background			none
background_opacity				0.8
